### ISSUE TITLE
Keynote template for everyone 

### ISSUE THREAD

**Issue by djtoro** [TORO-IO/hei-workshop#13]

**Comment by pongstr** [comment]
wip ref 29ce54318635c3cfd8b587f1052fb81e421a570c

**Comment by devcsrj** [comment]
Btw, will each speaker have a separate hosted presentation?

Since we're using [`reveal.js`](https://github.com/hakimel/reveal.js) as the presentation framework, I was thinking if we could have just one Presentation with *at least* 7 horizontally-divided slide (7 topics),  where:

| Welcome Slide | Building RESTful.. | ..Spring Security | ..Angular pt1   |
|-------------|--------------------|-------------------|-----------------|
|             | Topic 1 Slide 1    | Topic 2 Slide 1   | Topic 3 Slide 1 |
|             | Topic 1 Slide 2    | Topic 2 Slide 2   | Topic 3 Slide 2 |
|             | Topic 1 Slide 3    | Topic 2 Slide 3   | Topic 3 Slide 3 |

 > All topics are grouped vertically.

This way, we can host the whole presentation in `hei-workshop/gh-pages` branch (or our own machine in our laptop), and attendees will just need to visit one link.

WDYT?

**Comment by pongstr** [comment]
> Btw, will each speaker have a separate hosted presentation?

Not necessarily, once everyone has committed their presentation to the repo, we're able to deploy this remotely somewhere (err Heroku)

However, speakers has to add their own presentation, see [here](https://github.com/TORO-IO/hei-workshop/blob/master/slides/README.md), then PR once done.

> Since we're using reveal.js as the presentation framework, I was thinking if we could have just one 
> Presentation with at least 7 horizontally-divided slide (7 topics), where...

I don't think this is a good idea, here's why:

1. we want the audience to access these slides according to the topic they'd like to learn, digging through a single presentation is just an unnecessary effort.
1. the slideshow is static, contents are directly written in the html file, to have multiple topics in a single presentation will look chaotic.
1. everyone committing to a single file could also lead to a potential uncontrollable chaos.

Mainly, separating concerns can keep the presentation slides less complicated.

> This way, we can host the whole presentation in hei-workshop/gh-pages branch 
> (or our own machine in our laptop), and attendees will just need to visit one link.

All that's needed is for speakers to add their slide here and we'll take care of where its going to be deployed

:dancer:

**Comment by devcsrj** [comment]
> we want the audience to access these slides according to the topic they'd like to learn, digging through a single presentation is just an unnecessary effort.

+1. I'm sold.
