### ISSUE TITLE
App API Authentication

### ISSUE THREAD

**Issue by pongstr** [TORO-IO/hei-workshop#5]
In relation to #4, I think there has to be an authentication endpoint where a node server will have an initial post with user credentials to api server.

**Why?**

By default, browsers will not enable a client request due to CORS see [here](https://www.w3.org/TR/cors/). The proper process would be:

1. Angular App posts user-credentials to its node.js server
2. Node.js server then posts these credentials to API server
3. API server returns appropriate credential tokens back to node.js server
4. Node.js server adds these to browser cookies
5. Angular App then attaches cookie values as a header or as request parameters to every request.

```
          [ angular app ] → → → → → → → → → → → → → → → → → →  attaches these tokens/session-id
            Initial Post ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← to every request as an auth pass 
        ( user credentials)                                         ↓ ↑
              ↓   ↑                                                 ↓ ↑
              ↓   ↓ node.js then saves these token or               ↓ ↑
              ↓   ↑ session-id values as a cookie                   ↓ ↑ Angular App can now
              ↓   ↑                                                 ↓ ↑ directly make requests
        [ node.js server ]                                          ↓ ↑ to api-server for as long
              ↓   ↑                                                 ↓ ↑ as auth pass is valid
              ↓   ↑                                                 ↓ ↑
              ↓   ↑                                                 ↓ ↑
proxy request ↓   ↑ when validated, api-server                      ↓ ↑
to api-server ↓   ↑ then returns either tokens or session-id        ↓ ↑
              ↓   ↑ as auth pass for every request.                 ↓ ↑
              ↓   ↑                                                 ↓ ↑
              ↓   ↑                                                 ↓ ↑
          [ api-server ] ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ← ←  ↑
    validates user-credentials → → → → → → → → → → → → → → → → → → → 
  api-server should specify whether
  these auth pass should be attached
  with request headers or parameters
```

//cc @KuroNoDev

**Comment by devcsrj** [comment]
Hoho nice diagram! :+1: 

> By default, browsers will not enable a client request due to CORS...

Correct. So the angular app (client-side) can't directly do ajax requests to the server RESTful endpoints. Thus, your node.js server (NS) needed to do the proxy.

Re: **Authentication endpoint**
Just to be clear, this does **not** cause the CORS issue. This shouldn't block the progress of the UI development.

For the first iteration of the api server, you can freely request to the endpoints through your own NS, which in turn, is the endpoint the angular app uses. If @jerrickpua will discuss *implementing security to RESTful endpoints* (instead of AOP), then the 2nd iteration would indeed contain the implementation of the auth endpoint, most likely under `/api/login`.

For the authentication scheme, I see 2 simplest approach:
1. [Basic](https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side) - the NS need to always pass `Authorization` header containing `Basic: ` + base64-encoded, colon-separated username and password.
2. [JWT](http://jwt.io/) - which is explained in your model.

My only concern is the time required to discuss and implement the selected paths. They must be kept simple as possible, so that attendees can keep up - because most likely, there'll be lot's of questions like "what does that do?", or "para san yan?".

**Comment by devcsrj** [comment]
Another approach we can do (to keep things simple) is to remove altogether the NS, and move the entire frontend thinga-majigs in the final jar build. The [`web`](https://github.com/TORO-IO/hei-workshop/tree/master/app/web) directory would then reside in `api/src/main/resources`, which will be your working directory for `npm`, `bower`, etc commands.

I don't think you'd like this, but it's another approach so I'll leave it here.

**Comment by pongstr** [comment]
okay, as per meeting this morning maybe we can proceed to what has been agreed upon. closing this issue for now.
